export const COMPETITIONS = [
  'Alemanha - 2. Bundesliga',
  'Alemanha - Bundesliga',
  'Alemanha - DFB-Pokal',
  'América do Norte - CONCACAF Champions Cup',
  'América do Norte - Leagues Cup',
  'América do Sul - CONMEBOL Copa América',
  'América do Sul - CONMEBOL Libertadores',
  'América do Sul - CONMEBOL Recopa',
  'América do Sul - CONMEBOL Sudamericana',
  'Argentina - Copa Argentina',
  'Argentina - Copa de la Liga Profesional',
  'Argentina - Liga Profesional de Fútbol',
  'Bélgica - Croky Cup',
  'Bélgica - Jupiler Pro League',
  'Brasil - Campeonato Brasileiro Série A',
  'Brasil - Campeonato Brasileiro Série B',
  'Brasil - Copa do Brasil',
  'Escócia - Scottish Cup',
  'Escócia - Scottish Premiership',
  'Espanha - Copa del Rey',
  'Espanha - LALIGA EA SPORTS',
  'Espanha - LALIGA HYPERMOTION',
  'EUA - Major League Soccer (MLS)',
  'EUA - US Open Cup',
  'Europa - UEFA Champions League',
  'Europa - UEFA Conference League',
  'Europa - UEFA Euro',
  'Europa - UEFA Europa League',
  'Europa - UEFA Nations League',
  'Europa - UEFA Super Cup',
  'França - Coupe de France',
  'França - Ligue 1',
  'França - Ligue 2',
  'Holanda - Eredivisie',
  'Holanda - KNVB Beker',
  'Inglaterra - EFL Championship',
  'Inglaterra - EFL Cup (Carabao Cup)',
  'Inglaterra - FA Cup',
  'Inglaterra - Premier League',
  'Itália - Coppa Italia',
  'Itália - Serie A',
  'Itália - Serie B',
  'México - Copa MX',
  'México - Liga MX',
  'Mundial - Copa do Mundo da FIFA',
  'Mundial - Copa Intercontinental da FIFA',
  'Mundial - Mundial de Clubes da FIFA',
  'Portugal - Liga Portugal',
  'Portugal - Liga Portugal 2',
  'Portugal - Taça de Portugal',
  'Rússia - Russian Cup',
  'Rússia - Russian Premier League',
  'Uruguai - Campeonato Uruguayo',
  'Uruguai - Copa Uruguay',
] as const;
